name: Daily Weather Update

on:
  schedule:
    - cron: "0 14 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-weather:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        # requirements.txt varsa onu kur; yoksa minimumları kur
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install pandas requests
          fi

      - name: Run weather updater
        run: |
          python -u scripts/update_weather.py

      - name: Commit and push updated data
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add -A
          git commit -m "🌤️ Daily weather auto-update [skip ci]" || echo "No changes to commit"
          git push

